= Huami Web API Documents for Developers
Huami Tech <develop@huami.com>
:toc: left
:toclevels: 4
:toc-placement!:
:doctype: book
:icons: font
:source-highlighter: highlightjs

http://www.huami.com/[Huami] provides Web API for accessing user activity data tracked with Huami wearable-devices. Anyone can develop an application to access user's data on their behalf, as long as the user has granted consent to do so.

toc::[]

== 1. Overview

== 2. App Registration

Typically you need to provide information about an application such as:

. Application name
. An icon for the application

. URL to the application’s home page
. A short description of the application
. A link to the application’s privacy policy
. A list of redirect URIs

=== Redirect URIs

Redirect URIs are a critical part of the OAuth flow. After a user successfully authorizes an application, the authorization server will redirect the user back to the application with either an authorization code or access token in the URL. Because the redirect URI will contain sensitive information, it is critical that the service doesn’t redirect the user to arbitrary locations

=== Scopes

|====
|Scope|Description

|profile
|The profile scope is the basic user information

|activity
|The activity scope includes activity data, such as steps, distance, calories consumed, and active minutes

|sleep
|The sleep scope includes sleep logs and related sleep analysis, such as the sleep start time, wake time, the duration of sleep

|heartrate
|The heartrate scope includes the continuous heart rate data and related analysis

|motion
|The motion scope includes the active,sleep and related analysis data in minutes, every day has a data section, a section contains 1440(total minutes of one day)*3 bytes

|====

== 3. Authentication

=== Obtaining User Consent and Tokens (SDK for Native Mobile App)

=== Obtaining User Consent and Tokens (API for Web Site)

==== Huami OAuth Error Code

|====
|Http Status|code|message

|401
|0
|invalid token

|400
|-1001
|Error parameter

|400
|-1002
|Missing required parameter

|500
|-1003
|Internal server error

|400
|-1004
|Invalid parameter

|404
|-2001
|Not found

|400
|-2002
|Bad request

|====

=== Making Requests

To make a request to the HuaMi Data API using OAuth 2.0, simply add an Authorization header to the HTTP request with the user's access token.

*Example Request:*

[source,http,options="wrap"]
----
GET https://api-open.huami.com/users/-/profile
Authorization: Bearer TAQABAAAAAJ95lT4WrRdWtG3hog/0QvXTnUpL3FFxKOLBgm4JjIKJbSozXYxtltsQzBz0Z9PXDiIKBUOLMfjWX5Je6tGEdXLeaYeCEVS0dVYMWG+p+Y7avcVe0SWY4jITNGfuq/tlNLK9cACSkIW/L6Mnb9YNp4CzQDo7dU9WrxK87aOJ7gAlE4leZKeCM3+xLY3zRs3BGZEwrsCmEMqPr14rrD2KHny6aD2UvGQfXdVGVExe8jRbMLw2L2KdRWrxEW7vZRzXdw==
----

=== Access Token Request

*Request structure*

[source,http,options="nowrap"]
----
POST /oauth2/access_token HTTP/1.1
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Host: account.huami.com

client_id=clientId&client_secret=clientSecret&grant_type=refresh_token&redirect_uri=http%3A%2F%2Fwww.baidu.com&code=code
----

*Request parameters*

|===
|Parameter|Mandatory|Description

|`client_id`
|`Yes`
|Application ID issued by HuaMi when registered application

|`client_secret`
|`Yes`
|Application Secret

|`grant_type`
|`Yes`
|The grant_type parameter must be set to 'authorization_code'

|`redirect_uri`
|`Yes`
|This is the URI to which you want the user to be redirected after the authorization is complete. This must match the redirect URI that you have previously registered with the service

|`code`
|`Yes`
|Authorization Code

|===

*Example response*

[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: 617

{"access_token":"TAQABAAAAAJ95lT4WrRdWtG3hog/0QvXTnUpL3FFxKOLBgm4JjIKJbSozXYxtltsQzBz0Z9PXDiIKBUOLMfjWX5Je6tGEdXLeaYeCEVS0dVYMWG+p+Y7avcVe0SWY4jITNGfuq/tlNLK9cACSkIW/L6Mnb9YNp4CzQDo7dU9WrxK87aOJ7gAlE4leZKeCM3+xLY3zRs3BGZEwrsCmEMqPr14rrD2KHny6aD2UvGQfXdVGVExe8jRbMLw2L2KdRWrxEW7vZRzXdw==","token_type":"Bearer","expires_in":43200,"refresh_token":"TAQEBAAAAAC7iIWnqI4uE6UgCUiBRg887o9H48QS3IhW5b8c4aJQtyn2ED73TeJKxhWhxVg5+e5lM8Gv5il9FWbQjG5rDKCVnLZ2VGxqrcj6pcAXrLmOQeTePl9dF507jX3awUjQ9RIi7PQhD5MzOlvNIciBhy6hrxU2u5pLt0uTWTJC36blvkwAmdZXQwIpxz2cJPfgTKWGGM1v4IT8uWkYRMWnvYUWOXoPvubp7MRRdVPyngtcbq3aAYCMMmbHilZs8x/jALQ=="}
----

*Response fields*

|===
|Path|Type|Description

|`access_token`
|`String`
|Access token

|`token_type`
|`String`
|Token type

|`expires_in`
|`Number`
|Expire at some time stamp, UNIX time stamp(seconds)

|`refresh_token`
|`String`
|Refresh token, used to refresh access token

|===

*CURL request*

[source,bash]
----
$ curl 'https://account.huami.com/oauth2/access_token' -i -X POST -H 'Accept: application/json' -H 'Content-Type: application/x-www-form-urlencoded' -d 'client_id=clientId&client_secret=clientSecret&grant_type=refresh_token&redirect_uri=http%3A%2F%2Fwww.baidu.com&code=code'
----

=== Refreshing Tokens

*Request structure*

[source,http,options="nowrap"]
----
POST /oauth2/refresh_token HTTP/1.1
Authorization: Bearer TAQEBAAAAAC7iIWnqI4uE6UgCUiBRg887o9H48QS3IhW5b8c4aJQtyn2ED73TeJKxhWhxVg5+e5lM8Gv5il9FWbQjG5rDKCVnLZ2VGxqrcj6pcAXrLmOQeTePl9dF507jX3awUjQ9RIi7PQhD5MzOlvNIciBhy6hrxU2u5pLt0uTWTJC36blvkwAmdZXQwIpxz2cJPfgTKWGGM1v4IT8uWkYRMWnvYUWOXoPvubp7MRRdVPyngtcbq3aAYCMMmbHilZs8x/jALQ==
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Host: account.huami.com

client_id=2882303761517363510&client_secret=gwsORlhbQn1MpWheXJJx2w%3D%3D&grant_type=refresh_token
----

*Request headers*

|===
|Name|Description

|`Authorization`
|Auth credentials,The format should be assigned 'Bearer refresh_token'

|===

*Request parameters*

|===
|Parameter|Mandatory|Description

|`client_id`
|`Yes`
|Application ID issued by HuaMi when registered application

|`client_secret`
|`Yes`
|Application Secret

|`grant_type`
|`Yes`
|The grant_type parameter must be set to 'refresh_token'

|===

*Example response*

[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: 617

{"access_token":"TAQABAAAAAJ95lT4WrRdWtG3hog/0QvXTnUpL3FFxKOLBgm4JjIKJbSozXYxtltsQzBz0Z9PXDiIKBUOLMfjWX5Je6tGEdXLeaYeCEVS0dVYMWG+p+Y7avcVe0SWY4jITNGfuq/tlNLK9cACSkIW/L6Mnb9YNp4CzQDo7dU9WrxK87aOJ7gAlE4leZKeCM3+xLY3zRs3BGZEwrsCmEMqPr14rrD2KHny6aD2UvGQfXdVGVExe8jRbMLw2L2KdRWrxEW7vZRzXdw==","token_type":"Bearer","expires_in":43200,"refresh_token":"TAQEBAAAAAC7iIWnqI4uE6UgCUiBRg887o9H48QS3IhW5b8c4aJQtyn2ED73TeJKxhWhxVg5+e5lM8Gv5il9FWbQjG5rDKCVnLZ2VGxqrcj6pcAXrLmOQeTePl9dF507jX3awUjQ9RIi7PQhD5MzOlvNIciBhy6hrxU2u5pLt0uTWTJC36blvkwAmdZXQwIpxz2cJPfgTKWGGM1v4IT8uWkYRMWnvYUWOXoPvubp7MRRdVPyngtcbq3aAYCMMmbHilZs8x/jALQ=="}
----

*Response fields*

|===
|Path|Type|Description

|`access_token`
|`String`
|Access token

|`token_type`
|`String`
|Token type

|`expires_in`
|`Number`
|Expire at some time stamp, UNIX time stamp(seconds)

|`refresh_token`
|`String`
|Refresh token, used to refresh access token

|===

*CURL request*

[source,bash]
----
$ curl 'https://account.huami.com/oauth2/refresh_token' -i -X POST -H 'Authorization: Bearer TAQEBAAAAAC7iIWnqI4uE6UgCUiBRg887o9H48QS3IhW5b8c4aJQtyn2ED73TeJKxhWhxVg5+e5lM8Gv5il9FWbQjG5rDKCVnLZ2VGxqrcj6pcAXrLmOQeTePl9dF507jX3awUjQ9RIi7PQhD5MzOlvNIciBhy6hrxU2u5pLt0uTWTJC36blvkwAmdZXQwIpxz2cJPfgTKWGGM1v4IT8uWkYRMWnvYUWOXoPvubp7MRRdVPyngtcbq3aAYCMMmbHilZs8x/jALQ==' -H 'Accept: application/json' -H 'Content-Type: application/x-www-form-urlencoded' -d 'client_id=2882303761517363510&client_secret=gwsORlhbQn1MpWheXJJx2w%3D%3D&grant_type=refresh_token'
----

== 4. Accessing Data

=== User

=== Activity

=== Sleep

=== Heartbeat

=== Motion in Minutes

== 5. Subscriptions

== 6. Help